### ISSUE TITLE
Promise support for `onComplete`

### ISSUE THREAD

**Issue by edbzn** [hirezio/observer-spy#1]
Hi, 

It could simplify the code if we can use the async await syntax with `onComplete` method instead of a callback.

```ts
it('should work with promises', async () => {
  const observerSpy: ObserverSpy<string> = new ObserverSpy();

  const fakeService = {
    getData() {
      return Promise.resolve('fake data');
    },
  };
  const fakeObservable = of('').pipe(switchMap(() => fakeService.getData()));

  fakeObservable.subscribe(observerSpy);

  await observerSpy.onComplete();
  expect(observerSpy.getLastValue()).toEqual('fake data');
});
```

It removes the need to use Jest `done` fn and looks more synchronous, what do you think?

**Comment by shairez** [comment]
That's a good idea @edbzn !

Maybe we can support both ways (just in case)

wanna create a PR for it?

**Comment by edbzn** [comment]
Sounds good, I will do it soon.

**Comment by shairez** [comment]
Awesome thanks!
