### ISSUE TITLE
DISCUSSION 1: ObserverSpy API - Methods vs getters

### ISSUE THREAD

**Issue by shairez** [hirezio/observer-spy#13]
Following #12 by the amazing @ThomasBurleson we had a discussion and realized this PR could be separated into several PRs, and before that we need to discuss them. 

This discussion is about the possible changes to the ObserverSpy API to make it more "getters" focused.

## The suggested API changes to `ObserverSpy` - 

```ts

private _state: ObserverState<T> = {
    values: [],
    errorValue: undefined,
    called: {
      next: false,
      error: false,
      complete: false,
    },
  };

get state(): ObserverState<T> {
    return {
      ...this._state,
      values: [...this._state.values],
    };
  }

  get values(): T[] {
    return this._state.values;
  }

  get hasValues(): boolean {
    return this._state.values.length > 0;
  }

  get isComplete(): boolean {
    return this._state.called.complete;
  }

  readFirst(): T | undefined {
    return this.hasValues ? this._state.values[0] : undefined;
  }

  readLast(): T | undefined {
    return this.hasValues ? this._state.values[this._state.values.length - 1] : undefined;
  }

```

## The upsides (IMO) - 

- Read only values (that's a good idea to implement regardless of the api)

- Reduces the need to call a method which might make it shorter and more straightforward to read the state of the spy

- (probably more that I'm missing...)

## The downsides (IMO) - 
- `State` object usage might make the expectation longer and requires remembering more of api.
For example: 

```ts
expect(observerSpy.state.called.next).toBeTruthy();
// VS
expect(observerSpy.receivedNext()).toBeTruthy();

// AND

expect(observerSpy.getError()).toBe('OMG AN ERROR!');
// VS
expect(observerSpy.state.errorValue).toBe('OMG AN ERROR!');
```

- I prefer to reduce the nesting, so If we'll decide to go for getters, I would suggest flattening the api of "state" to exposed from the root, something like `observerSpy.errorValue` etc)

- Intuitively (for me), methods feel (at first glance) more "Read only" than properties, but maybe it's just me. 

- It's true that with TypeScript you'll see a compile time error if you try to assign `values` some other value, but with JS you'll get a run time error which is no fun. 
  It might be tempting for developers in some scenarios to try and do `observerSpy.values[2] = 'some other value';`, but then again, maybe I'm wrong here. 

---

Because this is a BREAKING_CHANGE, I wanted to get as much opinions as possible about it, before we decide whether we should break it into it's own PR. 

So @ThomasBurleson @katharinakoal @edbzn @burkybang @yjaaidi (and anyone else who'd like to chime in) - 

### **WHAT ARE YOUR THOUGHTS?**

**Comment by katharinakoal** [comment]
Well, that's a very interesting suggestion!
I like that the new API approach clearly hints that spy instances are stateful. That might benefit the readability of test specs where you want to go beyond checking basic behavior.

Maybe it would be helpful here to consider where this library will be heading to. What's your vision @shairez ? 🤩
If ObserverSpies should someday evolve to a comprehensive scheduler-free alternative to marble-testing, I would move forward with the new API suggestions.

Right now, I use ObserverSpies more like a supplement to marble-testing and like the simplicity of its API. That's why I rather prefer the current way of exposing only methods with prefixes (is/has/on/get). Each method has its decisive intention, and it feels somehow more consistent.

But that's just my opinion. I'm curious to see what's next. And if there is anything I can help with, let me know!

**Comment by shairez** [comment]
Thanks @katharinakoal for your feedback!

My aim for this library is to keep it small and simple.
That's why I like a more flattened API (vs nested). 

And that's where Thomas wanted to take this library too - towards an API he believes is better and simpler than the current one. 

I actually didn't plan to replace marble testing, just to make 90% of the every day app use cases easier to test :)

The question in this issue I believe comes down to - which is better - `.getValues()` or `.values` (and the rest of them)

I'm trying to find reasons other than "I like this style better because I'm used to it", but to actually show how it is saving time while reducing confusion. 

So maybe something like "In the following test, look how this api is much cleaner and clearer" (followed by a code example)

I know my experience is just one man's experience, so I try to incorporate as many perspectives as I can to make sure we have an API that covers as much use cases while keeping it elegant and small.

**Comment by NetanelBasal** [comment]
Hey Guys!

- Regarding the usage of methods or getters, I think it's a matter of preference. If we take a look at Sinon.JS, we'll see that most of its API are methods. One benefit of using methods is that they're scalable to changes without introducing a breaking change. For example, they can take additional parameters.
- IMHO the API should be simple and thin. Most of the usage will be to check the current value that was emitted.

**Comment by shairez** [comment]
Good points @NetanelBasal !
Thanks for sharing your feedback 🙏

**Comment by yjaaidi** [comment]
Hey everyone! 
+1 for **flat** in favor of nested.

Concerning properties vs methods, I like how properties are shorter... but even if we ignore extensibility by adding parameters, the problem we get is the inconsistency between using props for `values` and methods for things like `getValueAt()`. 

I think that the most important thing here is consistency. For instance, `hasReceivedNext() & getValues()` vs `receivedNext() & values()`.

I generally prefer the latest as it's shorted but we have to make sure that we'll never use any properties to be the least surprising.

**Comment by shairez** [comment]
Appreciate the feedback @yjaaidi !

I agree with your points and also that shorter is better, though `getValues()` feels better to me than `values()` (maybe it's a matter of being used to it or something)

**Comment by shairez** [comment]
Finally I had some time to get back to these issues 😅

I'm closing this issue as it seems like the majority thinks it's better to stay with methods. 

Thanks everyone for participating!

BTW, You can view the latest release with @ThomasBurleson 's improvements here -

https://github.com/hirezio/observer-spy/releases/tag/v1.4.0
