### ISSUE TITLE
is there a method to count the number of times the source observable has emitted?

### ISSUE THREAD

**Issue by chan-dev** [hirezio/observer-spy#22]
For example in the testing debounce, 
I would like to know how many times the source observable has emitted.

i have this example:
```
    const observerSpy = subscribeSpyTo(component.posts$ as Observable<Post[]>);

    component.searchTermSubject.next('t');
    tick(100);

    component.searchTermSubject.next('te');
    tick(300);

    component.searchTermSubject.next('test');
    tick(300);

    observerSpy.unsubscribe();
   
    // sample method
    expect(observableSpy.getEmissionCount()).toEqual(2);
```

Would that be possible?

**Comment by shairez** [comment]
Sounds like `observerSpy.getValuesLength()` 

Does it solve your issue?

**Comment by chan-dev** [comment]
I tried it but it seems like it counts the number of values on the observable not the actual emission.

**Comment by shairez** [comment]
Yep, this library is good for checking the **output** of the observable chain that is under test, which most of the time is the only thing you'd care about.

Why does it matter how many emissions the source observable emitted? (sounds like implementation details that'll make it harder to refactor the code in the future without breaking the tests).

**Comment by chan-dev** [comment]
you're right, maybe i'm just testing it the wrong way. Just started learning testing and It just occured to me that i'm basically testing the `debounceTime` operator in this case. Anyway, thanks for the response.

**Comment by shairez** [comment]
No problem!

You can join my [free Angular testing workshop here](https://learn.hirez.io/?utm_source=github&utm_medium=link&utm_campaign=observer-spy) (which should also send you a free testing course explaining the theory behind writing good tests)

That should provide you with a nice starting point to avoid mistakes

Happy testing and thanks for the report!
