### ISSUE TITLE
Jest matchers

### ISSUE THREAD

**Issue by rluvaton** [hirezio/observer-spy#27]
**Is your feature request related to a problem? Please describe.**
The extra `isEqual` and etc can make the test longer, if there were a custom matchers it will be much cleaner.

**Describe the solution you'd like**
```ts

import { subscribeSpyTo } from '@hirez_io/observer-spy';

it('should immediately subscribe and spy on Observable ', () => {
  const fakeObservable = of('first', 'second', 'third');

  // get a special observerSpy of type "SubscriberSpy" (with an additional "unsubscribe" method)
  // if you're using TypeScript you can declare it with a generic:
  // const observerSpy: SubscriberSpy<string> ... 
  const observerSpy = subscribeSpyTo(fakeObservable);

  // You can unsubscribe if you need to:
  observerSpy.unsubscribe();


  // EXPECTATIONS: 
  
  // .getFirstValue()
  expect(observerSpy).toFirstEmit('first');
  
  // .receivedNext()
  expect(observerSpy).toHaveBeenReceivedNext();
  
  // .getValues()
  expect(observerSpy).toEmitValues(fakeValues);
  
  // .getValuesLength()
  expect(observerSpy).toEmitValuesOfSize(3);
  
  // .getValueAt()
  expect(observerSpy).toEmitValueAt(1, 'second');
  
  // .getLastValue()
  expect(observerSpy).toLastEmit('third');
  
  // .receivedComplete()
  expect(observerSpy).toComplete();

});

```

**Comment by shairez** [comment]
Great idea @rluvaton!

My idea with this library is to keep it small and not dependent on any specific framework
I wonder if we can do it as either a separate library, or maybe a separate file... 🤔

**Comment by rluvaton** [comment]
I actually implement it with testing and all at my company...

I can create a PR if you like...

**Comment by shairez** [comment]
Thanks @rluvaton that would be great!
Can you make it in a way that people using jest will be able to import them from `@hirez_io/observer-spy/jest-matchers` ?

**Comment by rluvaton** [comment]
Hey, I've uploaded the config and the code to https://github.com/rluvaton/observer-spy-jest-matchers
But unfortunately, I'm very busy lately so maybe I'll make you a contributor and you could help?

**Comment by rluvaton** [comment]
> will be able to import them from `@hirez_io/observer-spy/jest-matchers`?

I don't think it's possible to create package with that name (I think only 1 slash allowed)

**Comment by shairez** [comment]
Thanks @rluvaton !
I meant if it was part of this repo, we could have export it from that path (without creating a new package), like importing from `@angular/routing/testing` for example.

As for the time issue, I'm in the same boat as you my friend 😅 
No worries, I can close this issue for now and when you'll have time to work on it any contribution will be greatly appreciated 

What do you say?

**Comment by rluvaton** [comment]
Sorry for the late reply, Sound good!

**Comment by MiniSuperDev** [comment]
Hello @shairez , is there any plan to add those matchers?
