### ISSUE TITLE
Support for RxJS 7

### ISSUE THREAD

**Issue by magne4000** [hirezio/observer-spy#41]
**Is your feature request related to a problem? Please describe.**
Support for RxJS 7, currently we have the following error message when trying to use the lib:
```
Cannot find module 'rxjs/internal/scheduler/AsyncScheduler' from 'node_modules/@hirez_io/observer-spy/dist/fake-time.js'
```

**Comment by shairez** [comment]
Thanks @magne4000 !

This is the same issue as #39 , so closing this in favor of the original issue
Will update this week
