### ISSUE TITLE
Await .onFirstEmitted() and .onEmitted(n); of observable values and then continue

### ISSUE THREAD

**Issue by JasonLandbridge** [hirezio/observer-spy#58]
First off, huge fan of observer-spy! What a life-saver!

**Is your feature request related to a problem? Please describe.**
Comparable to `.onComplete()` and `.onError()`, it would be very useful to have something that awaits the first or n value emitted by an observable before continuing. This is because not all observables should be completing and need to stay alive. [Observable Store](https://github.com/DanWahlin/Observable-Store) is a good example of this where I would like a (Vue) component to keep being updated when ever the store is updated, which means I don't want to complete the observable.

**Describe the solution you'd like**

Something like this maybe:

```javascript
const test$ = of([0,1,2,3,4,5,6,7,8,9,10]);
const _test= subscribeSpyTo(test$);

await _test.onFirstEmitted();
expect(_test.getFirstValue()).toEqual(0);

await _test.onEmitted(5);
expect(_test.getValues()).toEqual([0,1,2,3,4]);
```

**Describe alternatives you've considered**

Continuing from the example above:
```javascript
const test$ = of([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
const testTakeOne$ = test$.pipe(take(1));
const _testTakeOne = subscribeSpyTo(testTakeOne$);

await _testTakeOne.onComplete();
expect(_testTakeOne.getFirstValue()).toEqual(0);

const testTakeFive$ = test$.pipe(take(5));
const _testTakeFive = subscribeSpyTo(testTakeFive$);

await _testTakeFive.onComplete();
expect(_testTakeFive.getValues()).toEqual([0, 1, 2, 3, 4]);
```

**Additional context**
So before making this post I thought this couldn't be done but by rubber ducking I realized that it could be done, albeit in a convoluted way. If nothing else, I could most likely write an extension method for it. 

Thanks for reading and please like and subscribe if you want more feature requests!

**Comment by shairez** [comment]
Thanks @JasonLandbridge !
lol, I subscribed :)

I like the idea
I think I'd change `onEmitted` to `onCount` or `onValuesCount` to make it more clear.. 
because `onEmitted` might also be referring to the values themselves (like when the number 5 arrives, stop)

Mind creating a PR?

**Comment by JasonLandbridge** [comment]
Awesome, sure I will create something! Not to be outdone by your naming suggestion, maybe `onFirstValue` and `onValues` to be in line with `getFirstValue` and `getValues`? Or would that be confusing? Naming things is definitely the most difficult part of programming :p
Anyway, I will make something and the naming can always change so I will go start with your suggestion. :+1:

**Comment by JasonLandbridge** [comment]
So, this sounded good in theory but not so much in practice :sweat_smile: 

Consider the following:
```typescript
const arrayObservable$ = of(0,1,2,3,4,5,6,7,8,9,10);
const observerSpy: ObserverSpy<number> = new ObserverSpy();

const _subscription = arrayObservable$.subscribe(observerSpy)

await observerSpy.onValuesCount(5);

expect(observerSpy.getValues()).toEqual([0,1,2,3,4]);
```

Before the await is reached, the observable has already emitted all values from 0 to 10 at the moment the `.subscribe()` is called. Which makes the await useless as it instantly resolves due to the count being reached. 

A possibility here would be to add the `onValuesCount` before the subscription is called and then await after the subscription. 
So it would be something like this:

```typescript
const arrayObservable$ = of(0,1,2,3,4,5,6,7,8,9,10);
const observerSpy: ObserverSpy<number> = new ObserverSpy({valueCount: 5}); // Add the valueCount as a config property

const _subscription = arrayObservable$.subscribe(observerSpy)

await observerSpy.onValuesCount();

expect(observerSpy.getValues()).toEqual([0,1,2,3,4]);
```

This would "work", but then this is way more verbose than the following:

```typescript
const arrayObservable$ = of(0,1,2,3,4,5,6,7,8,9,10).pipe(take(5));  // Add the take(5) here which completes
const observerSpy: ObserverSpy<number> = new ObserverSpy();

const _subscription = arrayObservable$.subscribe(observerSpy)

await observerSpy.onComplete();

expect(observerSpy.getValues()).toEqual([0,1,2,3,4]);

```

So my proposed idea is worse then the simple addition of `.pipe(take(5))` and awaiting `observable$.onComplete()`. Which actually works perfectly with an observable that should stay alive in production but during testing you just need the first 5 values. 

Please let me know if I missed something that would make this idea viable!

**Comment by shairez** [comment]
Yes I agree that the extra ceremony makes it equivalent to just using plain RxJS

I can't think about a simple way from the top of my head, so unless you do, let's close this issue for now and revisit if a "A HA" moment will pop up in the shower 😊

Thanks again @JasonLandbridge !

**Comment by JasonLandbridge** [comment]
Haha I will keep it in mind, thanks for the consideration!
