### ISSUE TITLE
Simplify usage with factory function and internal subscription handling

### ISSUE THREAD

**Issue by katharinakoal** [hirezio/observer-spy#7]
Hey Shai!

Thanks for this! It makes basic observable testing a lot easier!
I replaced almost all marble tests in my current project using observer spies, and I do love them. When you don't have to make use of the complexity which comes with marble testing, observer spies are a real improvement in terms of clarity and readability.
However, I found the few lines to use them still a bit too implementation heavy ;) I know this is a matter of taste, so please consider this more like a feature proposal than a feature request.

**Is your feature request related to a problem? Please describe.**
Letting test authors handle subscriptions on their own leads to a bit too much boilerplate code.

**Describe the solution you'd like**
I ended up using observer spies like this:
```ts
const fakeObservable = of('first', 'second', 'third');
const spy = spyOnObservable(fakeObservable);

// if the observable under test will not complete
// or we just want the spy to stop listening
// this will internally unsubscribe
spy.stop();

// simplified shorthand usage
expect(spyOnObservable(fakeObservable).getFirstValue()).toBe('first');
```

For that to work, I extended the ObserverSpy Class to handle the subscription itself and added a stop method to give test authors the possibility to clear subscriptions:
```ts
class StoppableObserverSpy<T> extends ObserverSpy<T> {
  private observationStopped = new AsyncSubject<never>();

  constructor(observableUnderTest: Observable<T>) {
    super();
    observableUnderTest
      .pipe(
        finalize(() => this.stop()),
        takeUntil(this.observationStopped)
      )
      .subscribe(this);
  }

  public stop(): void {
    if (!this.observationStopped.isStopped) {
      this.observationStopped.complete();
      this.observationStopped.unsubscribe();
    }
  }
}
```
Additionally I use this simple factory function:
```ts
function spyOnObservable<T>(observableUnderTest: Observable<T>) {
  return new StoppableObserverSpy<T>(observableUnderTest);
}
```

**Describe alternatives you've considered**
Maybe the usage of observer spies could be simplified even more by creating custom jasmine/jest matchers, but I have no experience there.

**Additional context**
I guess the proposed modifications could be applied to this library without introducing breaking changes. If you think that these changes would be useful,  I'd love to create a PR for discussing implementation details.

Cheers,
kat

**Comment by shairez** [comment]
Hi @katharinakoal and thanks for the feedback! 😊 
Really happy to hear that it makes your observable tests easier.

And... I like your idea! I can see how it can simplify things, good job!

One thought I had about the name `spyOnObservable` is that it hides the fact that there is a subscription happening behind the scenes, and it might not be that obvious to people who read the code. 
(Usually spies don't trigger the action... but in this case they are)

But I like the fact that it is short, so I'm wondering whether it is worth signaling or not. 

Something like `spyOnObservableAndSubscribe` is too long and ugly IMO 😄 
but it shows the intent.  (maybe `subscribeAndSpyOnObservable`?, still long...)

What do you think?

(@edbzn , I'd love to hear your thoughts as well)

**Comment by katharinakoal** [comment]
Thanks for your feedback @shairez . I totally agree with you that hiding the point of subscription could be misleading in some scenarios. I'm still wondering if proper naming could even resolve this or if it might be better to go without the factory function.
But if we want to give it a try, how about just `subscribeAndSpyOn`?
Too bad that `spyscribe` already has a [meaning](https://www.urbandictionary.com/define.php?term=Spyscribe) 😄

**Comment by shairez** [comment]
HA HA I lolled so much! 😀
I keep learning new things every day... 

I like the `subscribeAndSpyOn` ... because "subscribe" already conveys the meaning that this is in the context of an Observable.

Spyscribe is a genius name... we could add it as an alias 😂

What do ya say? wanna move forward on this with a PR?

**Comment by katharinakoal** [comment]
Sure thing! I get on to it. 😊

**Comment by edbzn** [comment]
Hi there, I digged a bit in the custom matcher idea and it appears to be the common way to handle subscription and unsubscription when assertion function gets called. [Here](https://github.com/ReactiveX/rxjs/blob/cd7d64901e82fd7fb5e8407f1f30828906fac420/src/internal/testing/TestScheduler.ts#L134) in the TestScheduler source for example.

I feel this approach more natural than managing subscription in a spy, but at the same time writing custom matcher needs to address different test frameworks, and at the end it seems to be a lot more work. So I'm in favor of @katharinakoal `subscribeAndSpyOn` idea which is clear on what happen.

**Comment by shairez** [comment]
Thanks a lot @katharinakoal !

@edbzn I agree, having specific matchers means we need to support different frameworks, so it's better to minimize the peer dependencies. 

This could be an extension if it will be useful.

Thanks for the feedback!
